const categories=["Tous","Restaurants","Hôtels","Bars","Loisirs","Services"], accessibilityFilters=["Entrée sans marche","Toilettes accessibles","Ascenseur","Stationnement adapté","Chambre accessible"];
const places=[
{name:"Exemple – Café accessible",city:"Poitiers",category:"Restaurants",address:"Centre-ville, Poitiers",lat:46.583,lon:.34,phone:"05 49 00 00 01",hours:"Aujourd’hui : 08:00–19:00",website:"https://example.com",access:["Entrée sans marche","Toilettes accessibles"],details:["Entrée accessible de plain-pied","Toilettes adaptées","Espace de circulation accessible"]},
{name:"Exemple – Hôtel accessible",city:"Poitiers",category:"Hôtels",address:"Poitiers",lat:46.578,lon:.333,phone:"05 49 00 00 02",hours:"Accueil : 24 h/24",website:"https://example.com",access:["Ascenseur","Chambre accessible","Stationnement adapté"],details:["Ascenseur desservant les étages","Chambre accessible","Accès adapté à l'entrée","Stationnement adapté"]},
{name:"Exemple – Musée accessible",city:"Poitiers",category:"Loisirs",address:"Poitiers",lat:46.581,lon:.348,phone:"05 49 00 00 03",hours:"Aujourd’hui : 10:00–18:00",website:"https://example.com",access:["Entrée sans marche","Ascenseur"],details:["Entrée accessible","Ascenseur","Espaces de visite accessibles"]}];
let active="Tous",selectedAccess=new Set(),userMarker,userLat=null,userLon=null;
const cats=document.querySelector("#categories"),filters=document.querySelector("#accessFilters"),list=document.querySelector("#places"),search=document.querySelector("#search"),empty=document.querySelector("#empty");
const map=L.map("map").setView([46.5802,.3404],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);const placeLayer=L.layerGroup().addTo(map);
function rows(){const q=search.value.trim().toLowerCase();return places.filter(p=>(active==="Tous"||p.category===active)&&(!q||[p.name,p.city,p.category].join(" ").toLowerCase().includes(q))&&[...selectedAccess].every(f=>p.access.includes(f)))}
function render(){const r=rows();list.innerHTML="";r.forEach(p=>{list.insertAdjacentHTML("beforeend",'<article class="card"><h3>'+p.name+'</h3><div>'+p.city+' • '+p.category+'</div><div>'+p.access.map(x=>'<span class="tag">✓ '+x+'</span>').join("")+'</div><button class="details-btn place-details" data-index="'+places.indexOf(p)+'">Voir la fiche détaillée</button></article>')});empty.hidden=r.length>0;document.querySelectorAll(".place-details").forEach(b=>b.onclick=()=>openDetails(places[+b.dataset.index]));placeLayer.clearLayers();r.forEach(p=>L.marker([p.lat,p.lon]).addTo(placeLayer).bindPopup("<strong>"+p.name+"</strong><br>"+p.address))}
categories.forEach(c=>{const b=document.createElement("button");b.className="category";b.textContent=c;b.setAttribute("aria-pressed",c==="Tous");b.onclick=()=>{active=c;document.querySelectorAll("#categories .category").forEach(x=>x.setAttribute("aria-pressed",x.textContent===active));render()};cats.appendChild(b)});
accessibilityFilters.forEach(f=>{const b=document.createElement("button");b.className="category";b.textContent=f;b.setAttribute("aria-pressed","false");b.onclick=()=>{selectedAccess.has(f)?selectedAccess.delete(f):selectedAccess.add(f);b.setAttribute("aria-pressed",selectedAccess.has(f));render()};filters.appendChild(b)});
function openDetails(p){document.querySelector("#detailTitle").textContent=p.name;document.querySelector("#detailMeta").textContent=p.address+" • "+p.category;document.querySelector("#detailPhone").textContent=p.phone;document.querySelector("#detailHours").textContent=p.hours;document.querySelector("#detailWebsite").href=p.website;const route=document.querySelector("#detailRoute");route.onclick=(e)=>{e.preventDefault();const openRoute=(fromLat,fromLon)=>{const url="https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route="+fromLat+"%2C"+fromLon+"%3B"+p.lat+"%2C"+p.lon;window.open(url,"_blank")};if(userLat!==null&&userLon!==null){openRoute(userLat,userLon)}else if(navigator.geolocation){navigator.geolocation.getCurrentPosition(pos=>{userLat=pos.coords.latitude;userLon=pos.coords.longitude;openRoute(userLat,userLon)},()=>alert("La position est nécessaire pour calculer l’itinéraire depuis votre emplacement."))}};document.querySelector("#detailAccess").innerHTML=p.details.map(x=>"<li>✓ "+x+"</li>").join("");document.querySelector("#detail").hidden=false;document.querySelector("#detail").scrollIntoView({behavior:"smooth"})}
document.querySelector("#closeDetail").onclick=()=>document.querySelector("#detail").hidden=true;search.addEventListener("input",render);render();
document.querySelector("#nearMe").onclick=()=>{const s=document.querySelector("#locationStatus");s.textContent="Recherche de votre position…";navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude,lon=pos.coords.longitude;userLat=lat;userLon=lon;if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([lat,lon]).addTo(map).bindPopup("<strong>Votre position</strong>").openPopup();map.setView([lat,lon],14);s.textContent="Votre position est affichée sur la carte. Connexion Acceslibre prête : les lieux réels seront activés dès réception de la clé API."},()=>s.textContent="La localisation n’a pas été autorisée.")};
const addBtn=document.querySelector("#addPlaceBtn"),addForm=document.querySelector("#addPlaceForm"),addStatus=document.querySelector("#addPlaceStatus");
addBtn.onclick=()=>{addForm.hidden=!addForm.hidden;if(!addForm.hidden)document.querySelector("#newPlaceName").focus()};
addForm.onsubmit=e=>{e.preventDefault();const name=document.querySelector("#newPlaceName").value.trim(),city=document.querySelector("#newPlaceCity").value.trim(),category=document.querySelector("#newPlaceCategory").value;if(!name||!city){addStatus.textContent="Indiquez le nom du lieu et la ville.";return}addStatus.textContent="Merci. Votre proposition « "+name+" » à "+city+" est prête à être envoyée dès que le système de contributions sera connecté.";addForm.reset();};
